enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "@nrwl/devkit@*":
    dependencies:
      "nx": "latest"
  "@rollup/plugin-typescript@*":
    dependencies:
      "tslib": "latest"
  "debug@*":
    dependencies:
      "supports-color": "latest"
  "rollup@*":
    dependencies:
      "source-map-support": "latest"
      "supports-color": "latest"
  "typescript-transform-paths@*":
    dependencies:
      "@types/node": "latest"
      "ts-node": "latest"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-stage.cjs
    spec: "@yarnpkg/plugin-stage"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: loose

yarnPath: .yarn/releases/yarn-3.6.1.cjs
